#privileged: true requires to specify DRONE_ADMIN=username as env variable

pipeline:
  sonar-scanner:
    image: aosapps/drone-sonar-plugin
    secrets: [sonar_host, sonar_token]
    sources: iMXDemo
    when:
      event:
        - push
        - pull_request
  gitter:
    image: plugins/gitter
    secrets: [gitter_webhok]
  docsToRepo: # pushing the docs back to the repo
    image: plugins/git
    commands:
       - cd ./doxygen
       - git config --global user.email "drone@tillwitt.de"
       - git config --global user.name "Drone"
       - git status
       - git add --all
       - git commit -am "updated doxygen and sphinxdocs [CI SKIP]"
       - git push --set-upstream origin master
  slack: # pushing out notification
    image: plugins/slack:latest
    channel: dev
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
branches: master
