#privileged: true requires to specify DRONE_ADMIN=username as env variable

pipeline:
  sonar-scanner:
    image: aosapps/drone-sonar-plugin
    secrets: [sonar_host, sonar_token]
    sources: iMXDemo
    when:
      event:
        - push
        - pull_request
  gitter:
    image: plugins/gitter
    settings:
      webhook:
        from_secret: gitter_webhok
  slack: # pushing out notification
    image: plugins/slack:latest
    channel: dev
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
branches: master
